beanlibapi/apps/authx/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from dj_rest_auth.views import (
    LoginView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetConfirmView,
)
from dj_rest_auth.registration.views import (
    ResendEmailVerificationView,
)
from beanlibapi.apps.authx.views.base import (
    RegisterView,
    send_email,
    CustomEmailVerification,
)
from beanlibapi.apps.authx.views.google import (
    GoogleLoginView,
    GoogleConnectView,
)
from allauth.account.views import email as allauth_email_view

app_name = 'authx'

urlpatterns = []

urlpatterns += [
    path('signup/', RegisterView.as_view(), name='signup'),
    path('signin/', LoginView.as_view(), name='signin'),
    path('email/', allauth_email_view, name='account_email'),
    # path('resend-confirm-email/', CustomEmailVerification.as_view(), name='resend_confirm_email'),
    path('resend-confirm-email/', ResendEmailVerificationView.as_view(), name="rest_resend_email"),
    path('password/change/', PasswordChangeView.as_view(), name='password_change'),
    path('password/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/confirm/<str:uidb64>/<str:token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain'),
    # path('token/verify/', TokenObtainPairView.as_view(), name='token_obtain'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('email/send/', send_email, name='send_email'),
]

urlpatterns += [
    path('api/social-login/google/', GoogleLoginView.as_view(), name='google_login'),
    path('api/social-login/connect/google/', GoogleConnectView.as_view(), name='google_loginconnect'),
]

urlpatterns += [
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

beanlibapi/apps/core/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns

from beanlibapi.apps.core import views

app_name = 'core'

urlpatterns = []

urlpatterns += [
    path('bean/', views.BeanListCreateView.as_view()),
    path('bean/<str:pk>/', views.BeanRetrieveUpdateDestroyView.as_view()),
    # path('bean/upload/', views.BeanImageUploadView.as_view()),
    # path('attachments/uploads/', views.AttachmentUploadView.as_view()),
    # path('attachments/uploads/confirm/', views.AttachmentUploadConfirmView.as_view()),
    path('cafe/', views.CafeView.as_view()),
    path('cafe/<str:uid>/attach/', views.CafeDetailView.as_view())
    # path('/cafe/<str:pk>/', )
]


urlpatterns = format_suffix_patterns(urlpatterns)

beanlibapi/config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from beanlibapi.apps.core.views.base import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    # path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('i18n/', include('django.conf.urls.i18n')),

    path('authss/', include('allauth.urls')),
]

urlpatterns += [
    path('auth/', include('beanlibapi.apps.authx.urls')),
    # path('auth/', include('django.contrib.auth.urls')),
    path('core/', include('beanlibapi.apps.core.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    # path('api/csrf_token/', csrf_token_view, name='csrf_token'),
    path('', index),
]

beanlibapi/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from beanlibapi import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += [
    path('core/', include('beanlibapi.core.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    # path('api/csrf_token/', csrf_token_view, name='csrf_token'),
    path('', admin.site.urls),
]

beanlibapi/apps/authx/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from beanlibapi.apps.authx import model_managers as mm


class User(AbstractUser):
    email = models.EmailField(null=False, blank=False)
    deleted = models.BooleanField(db_index=True, null=True, blank=True)
    deleted_at = models.DateTimeField(db_index=True, null=True, blank=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)

    objects = mm.UserManager()

    def __str__(self):
        return self.username

beanlibapi/apps/core/models.py
import uuid
from django.conf import settings
from django.db import models

from beanlibapi.apps.core import model_managers as mm, model_mixins as mx

from shortid import ShortId

SID_GENERATOR = ShortId()


def generate_sid():
    return str(SID_GENERATOR.generate())


class Bean(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, db_index=True, unique=True, editable=False)
    name = models.CharField(max_length=255)
    region = models.CharField(max_length=255)
    variety = models.CharField(max_length=255)
    process = models.CharField(max_length=255)
    producer = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    is_active = models.BooleanField(default=True)

    objects = mm.BeanManager()

    class Meta:
        ordering = ['created_at']


class BeanDetail(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, db_index=True, unique=True, editable=False)
    bean_uid = models.ForeignKey(Bean, on_delete=models.CASCADE)
    context = models.JSONField(default=dict, blank=True)


class Cafe(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, db_index=True, unique=True, editable=False)
    name = models.CharField(max_length=255)
    images = models.JSONField(default=list, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True, editable=False)

    def __str__(self):
        return self.name


class Article(models.Model):
    uid = models.CharField(primary_key=True, max_length=24, unique=True, editable=False, default=generate_sid)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    is_deleted = models.BooleanField(default=False)
    view_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(db_index=True, auto_now=True)


class Attachment(models.Model, mx.AttachmentMixin):
    uid = models.CharField(primary_key=True, max_length=24, unique=True, editable=False, default=generate_sid)
    name = models.CharField(max_length=255)
    format = models.CharField(max_length=255)
    # image = models.FileField()
    # path = models.FilePathField(max_length=255)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    # owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # bean = models.ForeignKey('Bean', null=True, blank=True, on_delete=models.CASCADE)

beanlibapi/apps/authx/views/base.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render

from rest_framework.decorators import api_view
from rest_framework.views import APIView

from dj_rest_auth.registration.views import RegisterView as _RegisterView
from allauth.account.adapter import get_adapter

from beanlibapi.apps.authx.serializers import RegisterSerializer


class RegisterView(_RegisterView):
    serializer_class = RegisterSerializer

    def perform_create(self, serializer):
        user = super().perform_create(serializer)
        # Todo: logging
        return user


@api_view(['POST'])
def send_email(request, ):
    if request.method == "POST":
        send_mail(
            'Title',
            'Contentsss',
            from_email=settings.GMAIL_DEFAULT_SENDER,
            recipient_list=['ask4git@gmail.com'],
        )
    return render(request, 'email.html')


class CustomEmailVerification(APIView):
    def get(self, request):
        pass

    def post(self, request):
        adapter = get_adapter()
        adapter.is_email_verified()

beanlibapi/apps/authx/views/google.py
from django.conf import settings
from allauth.socialaccount.providers.google.views import GoogleOAuth2Adapter
from allauth.socialaccount.providers.oauth2.client import OAuth2Client
from dj_rest_auth.registration.views import SocialLoginView, SocialConnectView


class GoogleLoginView(SocialLoginView):
    adapter_class = GoogleOAuth2Adapter
    callback_url = settings.GOOGLE_OAUTH2_REDIRECT_URL
    client_class = OAuth2Client


class GoogleConnectView(SocialConnectView):
    adapter_class = GoogleOAuth2Adapter
    client_class = OAuth2Client

# # Temporary Deprecated
# def google_get_access_token(code):
#     token_response = requests.post(
#         "https://oauth2.googleapis.com/token",
#         params={
#             'client_id': settings.GOOGLE_OAUTH2_CLIENT_ID,
#             'client_secret': settings.GOOGLE_OAUTH2_CLIENT_SECRET,
#             'code': code,
#             'grant_type': 'authorization_code',
#             'redirect_uri': settings.GOOGLE_OAUTH2_REDIRECT_URL,
#             'state': 'random_string'
#         }
#     )
#
#     if not token_response.ok:
#         raise ValidationError('google_token is invalid')
#
#     access_token = token_response.json().get('access_token')
#     return access_token
#
# # Temporary Deprecated
# def google_get_userinfo(access_token):
#     userinfo_response = requests.get(
#         "https://www.googleapis.com/oauth2/v3/userinfo",
#         params={
#             'access_token': access_token
#         }
#     )
#
#     if not userinfo_response.ok:
#         raise ValidationError('Failed to obtain user info from Google.')
#
#     user_info = userinfo_response.json()
#     return user_info

beanlibapi/apps/core/views/attachment.py
from os import environ

from django.http import JsonResponse
from rest_framework import permissions as p, status
from rest_framework.generics import (
    CreateAPIView,

)
from rest_framework.parsers import MultiPartParser, FormParser, FileUploadParser
from rest_framework.response import Response
from beanlibapi.apps.core.utils.aws import create_presigned_post
from beanlibapi.apps.core import serializers as s
from shortid import ShortId
import os

SID_GENERATOR = ShortId()


def generate_sid():
    return str(SID_GENERATOR.generate())


def renaming_file_with_uid(file_name: str):
    _file_name, ext = os.path.splitext(file_name)
    replaced_file_name = "".join(_file_name.replace(" ", "_").split())
    return f"media/{replaced_file_name}_{generate_sid()}{ext}"


class AttachmentUploadView(CreateAPIView):
    permission_classes = [p.IsAuthenticated]

    # parser_classes = [MultiPartParser]
    # serializer_class = s.AttachmentSerializer

    def post(self, request, *args, **kwargs):
        bucket_name = environ['AWS_S3_BUCKET_NAME']
        file_name = request.data.get('name')
        object_name = renaming_file_with_uid(file_name)
        data = create_presigned_post(bucket_name, object_name,
                                     fields={"Content-Type": request.data.get('format')},
                                     conditions=[
                                         {"Content-Type": request.data.get('format')}
                                     ])
        data.update({"name": object_name})
        return JsonResponse(data=data, status=status.HTTP_201_CREATED)


class AttachmentUploadConfirmView(CreateAPIView):
    permission_classes = [p.IsAuthenticated]
    serializer_class = s.AttachmentSerializer

    # def create(self, request, *args, **kwargs):
    #     print(request.data)
    #     return Response(status=status.HTTP_201_CREATED)

beanlibapi/apps/core/views/base.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

beanlibapi/apps/core/views/bean.py
from rest_framework import permissions as p, status
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView, CreateAPIView,
)
from rest_framework.parsers import FileUploadParser
from rest_framework.response import Response

from beanlibapi.apps.core import serializers as s, models as m


# from beanlibapi.core.permissions import IsOwnerOrReadOnly


class BeanListCreateView(ListCreateAPIView):
    queryset = m.Bean.objects
    serializer_class = s.BeanSerializer
    permission_classes = [p.IsAuthenticatedOrReadOnly]


class BeanRetrieveUpdateDestroyView(RetrieveUpdateDestroyAPIView):
    queryset = m.Bean.objects
    serializer_class = s.BeanSerializer
    # permission_classes = [p.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    permission_classes = [p.IsAuthenticatedOrReadOnly]


class BeanImageUploadView(CreateAPIView):
    permission_classes = [p.IsAuthenticated]
    parser_classes = [FileUploadParser]

    def create(self, request, *args, **kwargs):
        return Response(status=status.HTTP_201_CREATED)

beanlibapi/apps/core/views/cafe.py
from django.http import JsonResponse
from rest_framework.generics import UpdateAPIView, RetrieveUpdateDestroyAPIView, CreateAPIView
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import permissions as p, status
from drf_rw_serializers.generics import (
    ListCreateAPIView,
)

from beanlibapi.apps.core.models import Cafe
from beanlibapi.apps.core.serializers import CafeSerializer, CafeDetailSerializer, CafeWriteSerializer
from beanlibapi.apps.core.permissions import IsOwnerOrReadOnly


class CafeView(ListCreateAPIView):
    queryset = Cafe.objects.all()
    serializer_class = CafeSerializer
    read_serializer_class = CafeSerializer
    write_serializer_class = CafeWriteSerializer
    permission_classes = [p.IsAuthenticatedOrReadOnly]

    def preform_create(self, serializer):
        serializer.save(owner=self.request.user)

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)

        if not serializer.is_valid():
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        self.preform_create(serializer)
        return Response(serializer.data, status=status.HTTP_201_CREATED)


class CafeDetailView(UpdateAPIView):
    queryset = Cafe.objects.all()
    permission_classes = [IsOwnerOrReadOnly]
    serializer_class = CafeDetailSerializer
    lookup_field = 'uid'

    # def preform_create(self, serializer):
    #     serializer.save(owner=self.request.user)

    # def get_object(self):
    #     cafe = Cafe.objects.get(pk=self.kwargs['pk'])

    # def post(self, request, *args, **kwargs):
    #     print(kwargs.get('uid'))
    #     images = request.data.get('images')
    #     return Response({'images': images}, status=status.HTTP_200_OK)

beanlibapi/core/views.py
from rest_framework import permissions as p
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
)

from dj_rest_auth.registration.views import (
    RegisterView as _RegisterView,
    LoginView as _LoginView
)

from beanlibapi.core import (
    models as m,
    serializers as s,
)


# from beanlibapi.core.permissions import IsOwnerOrReadOnly


class RegisterView(_RegisterView):
    serializer_class = s.RegisterSerializer


class LoginView(_LoginView):
    serializer_class = s.LoginSerializer


class BeanListCreateView(ListCreateAPIView):
    queryset = m.Bean.objects
    serializer_class = s.BeanSerializer
    permission_classes = [p.IsAuthenticatedOrReadOnly]


class BeanRetrieveUpdateDestroyView(RetrieveUpdateDestroyAPIView):
    queryset = m.Bean.objects
    serializer_class = s.BeanSerializer
    # permission_classes = [p.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    permission_classes = [p.IsAuthenticatedOrReadOnly]

beanlibapi/core/views/bean.py
from rest_framework import permissions as p, status
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView, CreateAPIView,
)
from rest_framework.parsers import MultiPartParser, FormParser, FileUploadParser
from rest_framework.response import Response

from beanlibapi.core import (
    models as m,
    serializers as s,
)


# from beanlibapi.core.permissions import IsOwnerOrReadOnly


class BeanListCreateView(ListCreateAPIView):
    queryset = m.Bean.objects
    serializer_class = s.BeanSerializer
    permission_classes = [p.IsAuthenticatedOrReadOnly]


class BeanRetrieveUpdateDestroyView(RetrieveUpdateDestroyAPIView):
    queryset = m.Bean.objects
    serializer_class = s.BeanSerializer
    # permission_classes = [p.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    permission_classes = [p.IsAuthenticatedOrReadOnly]


class BeanImageUploadView(CreateAPIView):
    permission_classes = [p.IsAuthenticated]
    parser_classes = [FileUploadParser]

    def create(self, request, *args, **kwargs):
        return Response(status=status.HTTP_201_CREATED)

beanlibapi/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <link rel="icon" href="{% static 'images/bean-library-favicon.ico' %}" type="image/x-icon">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Bean-Library</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

beanlibapi/templates/email.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>Gmail using Django</title>
</head>
<body>
<div style="text-align:center;">
    <h4> 연락 정보 </h4>
    <form method="POST" action="{% url 'authx:send_email' %}">
        {% csrf_token %}
        <input type="text" name="name" placeholder="이메일 제목" required>
        <br>
        <br>
        <input type="email" name="email" placeholder="이메일 주소" required>
        <br>
        <br>
        <textarea name="message" placeholder="메시지 입력" required></textarea>
        <button type="submit">전송</button>
    </form>
</div>
</body>
</html>

beanlibapi/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
    <div class="alert alert-danger">
        {% for field in form %}
            <!-- 필드 오류 -->
            {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
        <!-- 넌필드 오류 -->
        {% for error in form.non_field_errors %}
            <div>
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}

beanlibapi/templates/index.html
{#{% load i18n %}#}
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div>
        <h1>Welcome to the Homepage!</h1>
        {% if user.is_authenticated %}
            <p>Hello, {{ user.username }}!</p>

            <form action="{% url 'account_logout' %}">
                <button type="submit">sign-out</button>
            </form>
        {% else %}
            <p>Hello, Guest!</p>
            <form action="{% url 'account_signup' %}">
                <button type="submit">Sign-In</button>
            </form>
{#            <form action="{% url 'accounts:signup' %}">#}
{#                <button type="submit">Sign-Up</button>#}
{#            </form>#}
{#            <form action="{% url 'core:sign-upup' %}">#}
{#                <button type="submit">sign-Up via allauth</button>#}
{#            </form>#}
        {% endif %}
        <p>This is the main landing page of the website.</p>
    </div>
{% endblock %}

beanlibapi/templates/login.html
{% extends "admin/base.html" %}
{% block content %}
    <div class="container my-3">
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label for="username">사용자ID</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password">비밀번호</label>
                <input type="password" class="form-control" name="password" id="password"
                       value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary">로그인</button>
        </form>
    </div>
{% endblock %}

beanlibapi/templates/signin.html
<!-- accounts/templates/signup.html -->
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="wrapper" style="text-align: center;">
        <h1>Sign-In</h1>
        <form method="POST">
            {% csrf_token %}
            Username: <input name="username" type="text">
            <br>
            Password: <input name="password" type="password">
            <br>
            <input type="submit" class="btn btn-primary" value="Sign In">
        </form>
    </div>
{% endblock %}

beanlibapi/templates/signup.html
<!-- accounts/templates/signup.html -->
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="wrapper" style="text-align: center;">
        <h1>Sign-Up</h1>
        <form method="POST">
            {% csrf_token %}
            Username: <input name="username" type="text">
            <br>
            Password: <input name="password1" type="password">
            <br>
            Confirm password: <input name="password2" type="password">
            <br>
            E-mail address: <input name="email" type="email">
            <br><br>
            <input type="submit" class="btn btn-primary" value="Sign-Up">
        </form>
    </div>
{% endblock %}

beanlibapi/templates/signup_form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>